### PR TITLE
Fix hide non related tones

### LINKED ISSUE #331: "Hide Non-Related Tones" is broken.
A test file is attached at https://musicology.epfl.ch/mattermost/dcml-student-projects/pl/5sbbzc5yfbboudrkm3nbanq39c.

### PR DESCRIPTION
**Pull request by Crowerade**
Fixes #331.

### CODE REVIEW

**Comment by yrammos** [comment]
@Crowerade the PR breaks the "hide stems etc." function of the app. This is easy to reproduce with any score.

**Comment by Crowerade** [comment]
Should be fixed!

File: src/js/action/delete.js [hunk 1]
```diff
@@ -32,8 +32,7 @@ function delete_relation(elem) {
   // Find all arcs related to this element
   var arcs =
     Array.from(mei.getElementsByTagName('arc')).filter((arc) => {
-      return arc.getAttribute('to') == '#' + elem.id ||
-              arc.getAttribute('from') == '#' + elem.id
+      return arc.getAttribute('from') == '#' + elem.id.slice(1)
```
Comment (yrammos) [inline src/js/action/delete.js]: Let's drop this change.

**Comment by Crowerade** [comment]
Creation of new layers should now not include reductions from previous layer

**Comment by yrammos** [comment]
@Crowerade this is an improvement, thanks.

**Comment by yrammos** [comment]
We have a bug that I am trying to reproduce. Please stay tuned!

**Comment by yrammos** [comment]
@Crowerade I reproduced the bug (which was inherited and not introduced by you):

1. Open an MEI score.
2. Reduce it several times (using the "Reduce" button).
3. Toggle "non-related tones" on and off.

Result: Some notes that were removed by the reduction will now reappear.

I am afraid this issue cannot be solved without fundamental changes to the app.

The reason is that the "reduce" function merely hides notes from the SVG; it does not remove them from the MEI.

As a result, when we hide/show hidden notes, we essentially reduce or reveal ("un-reduce") them using CSS. So the "hide non-related tones" algorithm does not know whether a note was 

The current algorithm is something like the following:

### Show non-related notes.

1. Select the current layer (the operation must be layer-specific!).
2. In the layer SVG, find all notes that been hidden using CSS attributes.
3. Remove that CSS attribute, so that these notes become visible.

### Hide non-related notes.

1. Select the current layer (the operation must be layer-specific!).
2. In the layer SVG, find all notes that are currently visible.
3. For each one of these notes, check in the MEI file whether they are members of any relation, and hide them if they are not.

### Question

Is this feature worth the effort? We need to think about that.

**Comment by Crowerade** [comment]
I think a simple solution would be to have two different classes that hide the notes (one for reduction, and another for unrelated notes). That way, they don't get mixed up

**Comment by Crowerade** [comment]
This should be fixed. If we don't want to keep the feature, we can drop the commit as well

File: src/js/action/delete.js (hunk 1 above)
Comment (yrammos) [reply src/js/action/delete.js]: @Crowerade if this change is intended as an optimization, and is not essential to implement this PR, let's drop it. It's a bit risky in the absence of formal unit testing.

File: src/js/modules/UI/utils/reductions.js [hunk 2]
```diff
@@ -78,7 +78,7 @@ function do_reduce(draw_context, mei_graph, sel, extra) {
 
   var remaining_relations = all_relations_nodes.filter((n) => {
     var g = get_by_id(document, draw_context.id_prefix + n.getAttribute('xml:id'))
-    return g != undefined && !g.classList.contains('hidden')
+    return g != undefined && !g.classList.contains('reduced')
```
Comment (yrammos) [inline src/js/modules/UI/utils/reductions.js]: @Crowerade I agree that "reduced" is more precise than the generic adjective "hidden."

However, I suggest that we keep "hidden" to avoid potential side-effects or bugs deep into this old codebase.

**Review by yrammos — CHANGES_REQUESTED** [review]
@Crowerade your alternative suggestion is a good compromise between usability and algorithmic complexity. Let's proceed as you suggest.

I have left a couple of minor comments in my code review.

File: src/js/action/delete.js (hunk 1 above)
Comment (Crowerade) [reply src/js/action/delete.js]: Yes, no problem. We only need to keep ` slice(1) ` and apply it to both ` from ` and ` to `.

File: src/js/modules/UI/utils/reductions.js (hunk 2 above)
Comment (Crowerade) [reply src/js/modules/UI/utils/reductions.js]: Do you mean to keep the current ` hidden ` class or to rename ` reduced ` to ` hidden-red ` (for instance)?
If we keep the ` hidden ` class, it might cause some inconsistencies when another part of the code handles ` hidden ` elements

File: src/js/action/delete.js (hunk 1 above)
Comment (Crowerade) [reply src/js/action/delete.js]: I just noticed, I think this change has already been applied in bf333f080a4f

File: src/js/modules/UI/utils/reductions.js (hunk 2 above)
Comment (yrammos) [reply src/js/modules/UI/utils/reductions.js]: @Crowerade I meant the former option: namely, to just keep the `hidden` class. This is because, most likely, every part of the app that handles `hidden` notes assumes they were hidden by reduction. (I suppose this is the reason why this bug exists in the first place.)

However, you do have a point, in the sense that this naming of classes is inconsistent, so I like your proposal in principle. If you search the entire codebase (`grep` ) for the keyword `hidden`, and confirm to me that renaming makes sense, then I can accept this revision.

Comment (Crowerade) [reply src/js/modules/UI/utils/reductions.js]: Yes, I think this makes sense, I will commit shortly a replacement for ` reduced ` in favour of ` hidden-reduced `

Comment (Crowerade) [reply src/js/modules/UI/utils/reductions.js]: It should now work as intended and be clearer to anyone who would read the code/html

File: src/js/action/delete.js (hunk 1 above)
Comment (Crowerade) [reply src/js/action/delete.js]: In fact, it was on another file, my mistake. I made a commit to fix that
