### PR TITLE
Fix relation hovering error

### LINKED ISSUE #339: Type error appearing in console when hovering a new layer's relation
Getting this error:
```
SES_UNCAUGHT_EXCEPTION: TypeError: can't access property "getAttribute", he is undefined

### PR DESCRIPTION
**Pull request by Crowerade**
Fixes #339.

### CODE REVIEW

File: src/js/action/draw.js [hunk 1]
```diff
@@ -504,9 +510,13 @@ function removeHoverClassToChildren(element, isRoot, isPrimary, draw_context, me
...
-    // Get the corresponding MEI node using the oldid attribute
-    // TODO: might be undefined and produce error
-    let meiNode = get_by_id(mei_graph, element.getAttribute('oldid') || element.id)
+    let meiNode = get_by_oldid(mei_graph, element.getAttribute('oldid'))
+    if (!meiNode) {
+      let id = element.id.slice(element.id.match(/^\d/))
+      meiNode = get_by_id(mei_graph, id)
+    }
+
+    if (!meiNode || !meiNode.length) return
```
Comment (yrammos) [inline src/js/action/draw.js:531]: @Crowerade aren't lines 513–519 identical with479–485? If so, it would be best to define a local function or a utility function (see DRY principle).

Comment (yrammos) [reply src/js/action/draw.js:531]: @Crowerade also, what was the root cause of the console error?

Comment (yrammos) [reply src/js/action/draw.js:531]: I am asking because I think that this PR breaks meta-relation deletion.

**Review by yrammos — CHANGES_REQUESTED** [review]

File: src/js/action/draw.js (hunk 1 above)
Comment (Crowerade) [reply src/js/action/draw.js:531]: > @Crowerade aren't lines 513–519 identical with479–485? If so, it would be best to define a local function or a utility function (see DRY principle).

Yes, I thought of doing that, I can do it in a following commit

Comment (Crowerade) [reply src/js/action/draw.js:531]: The cause was that the ID of the meta-relation would not be found and so subsequent function calls would not be valid on a ` null ` value.

Comment (Crowerade) [reply src/js/action/draw.js:531]: The PR should only remove the error, as it avoids having functions called on ` null ` values, so I don't think it is the cause for the meta-relation deletion problem.
I tested on other branches (and this one) and there is a meta-relation deletion problem on other layers than the first one. This sounds like another issue

Comment (Crowerade) [reply src/js/action/draw.js:531]: I added a new function to avoid repetition

**Comment by yrammos** [comment]
@Crowerade you're right, the issue with meta-relation deletion in layers originates in `develop`, not this PR.

I'll open an issue for it.
